from enum import Enum

class ReasonCode(str, Enum):
    ACCESS_BURST = "ACCESS_BURST"
    NEW_CONTRACT_SPIKE = "NEW_CONTRACT_SPIKE"
    VALUE_OUTLIER = "VALUE_OUTLIER"
    REPEATED_DENIALS = "REPEATED_DENIALS"
    KNOWN_PATTERN_SIMILARITY = "KNOWN_PATTERN_SIMILARITY"
    GEMINI_FRAUD_LIKE = "GEMINI_FRAUD_LIKE"
    GEMINI_POTENTIAL_ILLICIT = "GEMINI_POTENTIAL_ILLICIT"
    LOW_CONFIDENCE_REVIEW = "LOW_CONFIDENCE_REVIEW"
    COLD_START_WALLET = "COLD_START_WALLET"