"""Statistical anomaly detector (spec §5): scikit-learn IsolationForest.

Training data = "normal" behavior only:
  * repo-root normal_wallets.csv (generated by backend/generate_data.py) mapped
    onto MODEL_FEATURES, or
  * a deterministic synthetic normal population if that file is missing.
Fixed random_state => the same vector always gets the same score (repeatability test).
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

from app.api.settings import REPO_DIR
from app.features.baselines import PopulationStats
from app.features.schemas import MODEL_FEATURES, VECTOR_VERSION

log = logging.getLogger("potus.models")

RANDOM_STATE = 42
N_ESTIMATORS = 300

# Column mapping from generate_data.py output -> our feature names
CSV_MAP = {
    "tx_10m": "tx_count_10m",
    "tx_1h": "tx_count_1h",
    "unique_contracts_24h": "unique_contracts_24h",
    "new_contract_ratio": "new_contract_ratio",
    "access_requests_10m": "access_requests_10m",
    "failed_requests_1h": "failed_access_count",
    "flagged_counterparties": "flagged_counterparty_count",
}


def normalize_anomaly(raw_score: float, low: float, high: float) -> float:
    """Map raw model output (higher = more anomalous) into 0.0-1.0 for the risk engine."""
    x = (raw_score - low) / (high - low) if high > low else 0.0
    return float(max(0.0, min(1.0, x)))


def synthetic_normal(n: int = 1000, seed: int = RANDOM_STATE) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    return pd.DataFrame({
        "tx_count_10m": rng.poisson(2, n),
        "tx_count_1h": rng.poisson(8, n),
        "unique_contracts_24h": rng.poisson(4, n),
        "new_contract_ratio": rng.beta(2, 8, n),
        "transfer_value_zscore": np.clip(rng.normal(0, 1, n), -4, 4),
        "access_requests_10m": rng.poisson(1, n),
        "failed_access_count": rng.poisson(0.2, n),
        "flagged_counterparty_count": rng.binomial(1, 0.02, n),
    })[MODEL_FEATURES]


def load_training_frame(csv_path: Optional[Path] = None) -> tuple[pd.DataFrame, str]:
    csv_path = csv_path or (REPO_DIR / "normal_wallets.csv")
    if csv_path.exists():
        raw = pd.read_csv(csv_path)
        if set(CSV_MAP).issubset(raw.columns):
            df = raw.rename(columns=CSV_MAP)
            # avg_transfer_value is a level, not a z-score: standardize it (log-space) to a z-score proxy
            if "avg_transfer_value" in raw.columns:
                lv = np.log10(raw["avg_transfer_value"].clip(lower=1e-9))
                df["transfer_value_zscore"] = ((lv - lv.mean()) / (lv.std() or 1.0)).clip(-4, 4)
            else:
                df["transfer_value_zscore"] = synthetic_normal(len(df))["transfer_value_zscore"].values
            return df[MODEL_FEATURES].astype(float), f"csv:{csv_path.name}"
        log.warning("normal_wallets.csv columns unexpected; using synthetic normal data")
    return synthetic_normal().astype(float), "synthetic"


class AnomalyDetector:
    def __init__(self):
        self.model: Optional[IsolationForest] = None
        self.low = 0.0
        self.high = 1.0
        self.population = PopulationStats()
        self.trained_on = ""
        self.vector_version = VECTOR_VERSION

    # ---- training --------------------------------------------------------------
    def fit(self, df: pd.DataFrame, source: str = "") -> "AnomalyDetector":
        X = df[MODEL_FEATURES].to_numpy(dtype=float)
        self.model = IsolationForest(n_estimators=N_ESTIMATORS, contamination="auto", random_state=RANDOM_STATE)
        self.model.fit(X)
        raw = self._raw(X)
        # Calibration: median normal -> 0.0; anomaly 1.0 at median + 2.5 * (p99 - median).
        p50, p99 = float(np.percentile(raw, 50)), float(np.percentile(raw, 99))
        self.low = p50
        self.high = p50 + 2.5 * max(p99 - p50, 1e-6)
        self.population = PopulationStats(
            median={k: float(df[k].median()) for k in MODEL_FEATURES},
            mean={k: float(df[k].mean()) for k in MODEL_FEATURES},
            std={k: float(df[k].std() or 1.0) for k in MODEL_FEATURES},
        )
        self.trained_on = source
        return self

    # ---- scoring ---------------------------------------------------------------
    def _raw(self, X: np.ndarray) -> np.ndarray:
        # sklearn: decision_function > 0 normal, < 0 anomalous. Flip so higher = more anomalous.
        return -self.model.decision_function(X)

    def raw_score(self, vector: list[float]) -> float:
        if self.model is None:
            raise RuntimeError("detector not trained")
        return float(self._raw(np.asarray([vector], dtype=float))[0])

    def score(self, vector: list[float]) -> float:
        return round(normalize_anomaly(self.raw_score(vector), self.low, self.high), 4)

    def info(self) -> dict:
        return {
            "model": "IsolationForest",
            "n_estimators": N_ESTIMATORS,
            "random_state": RANDOM_STATE,
            "features": MODEL_FEATURES,
            "vector_version": self.vector_version,
            "trained_on": self.trained_on,
            "calibration": {"low": round(self.low, 5), "high": round(self.high, 5)},
        }
